checkpoint: /project/peilab/qjl/2026/wmrl/playground/wm/last.ckpt
output_dir: /project/peilab/qjl/2026/wmrl/lewm/eval/eval_outputs/libero_embed_eval
device: cuda
encode_chunk_t: 64
n_step_max: 10
n_step_list:
- 1
- 10
- 50
- 100
eval_task1: true
eval_task2: true
max_episodes: 30
max_starts_per_episode: null
progress_every_episode: true
seed: 3072
img_size: 224
patch_size: 14
encoder_scale: tiny
wm:
  type: lewm
  history_size: 3
  num_preds: 1
  embed_dim: 192
predictor:
  depth: 6
  heads: 16
  mlp_dim: 2048
  dim_head: 64
  dropout: 0.1
  emb_dropout: 0.0
data:
  dataset:
    type: libero
    root: /project/peilab/qjl/2026/playground/dataset/libero
    split: train
    num_steps: 4
    frameskip: 1
    keys_to_load:
    - pixels
    - action
    - state
    pixel_key: image
    max_episode_cache: 8
wandb:
  enabled: true
  project: lewm_eval
  entity: null
  name: libero_embed_eval
  tags:
  - lewm
  - libero
